// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package hw_trezor_messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Mapping between TREZOR wire identifier (uint) and a protobuf message
type MessageType int32

const (
	// Management
	MessageType_MessageType_Initialize             MessageType = 0
	MessageType_MessageType_Ping                   MessageType = 1
	MessageType_MessageType_Success                MessageType = 2
	MessageType_MessageType_Failure                MessageType = 3
	MessageType_MessageType_ChangePin              MessageType = 4
	MessageType_MessageType_WipeDevice             MessageType = 5
	MessageType_MessageType_GetEntropy             MessageType = 9
	MessageType_MessageType_Entropy                MessageType = 10
	MessageType_MessageType_LoadDevice             MessageType = 13
	MessageType_MessageType_ResetDevice            MessageType = 14
	MessageType_MessageType_Features               MessageType = 17
	MessageType_MessageType_PinMatrixRequest       MessageType = 18
	MessageType_MessageType_PinMatrixAck           MessageType = 19
	MessageType_MessageType_Cancel                 MessageType = 20
	MessageType_MessageType_ClearSession           MessageType = 24
	MessageType_MessageType_ApplySettings          MessageType = 25
	MessageType_MessageType_ButtonRequest          MessageType = 26
	MessageType_MessageType_ButtonAck              MessageType = 27
	MessageType_MessageType_ApplyFlags             MessageType = 28
	MessageType_MessageType_BackupDevice           MessageType = 34
	MessageType_MessageType_EntropyRequest         MessageType = 35
	MessageType_MessageType_EntropyAck             MessageType = 36
	MessageType_MessageType_PassphraseRequest      MessageType = 41
	MessageType_MessageType_PassphraseAck          MessageType = 42
	MessageType_MessageType_PassphraseStateRequest MessageType = 77
	MessageType_MessageType_PassphraseStateAck     MessageType = 78
	MessageType_MessageType_RecoveryDevice         MessageType = 45
	MessageType_MessageType_WordRequest            MessageType = 46
	MessageType_MessageType_WordAck                MessageType = 47
	MessageType_MessageType_GetFeatures            MessageType = 55
	MessageType_MessageType_SetU2FCounter          MessageType = 63
	// Bootloader
	MessageType_MessageType_FirmwareErase   MessageType = 6
	MessageType_MessageType_FirmwareUpload  MessageType = 7
	MessageType_MessageType_FirmwareRequest MessageType = 8
	MessageType_MessageType_SelfTest        MessageType = 32
	// Bitcoin
	MessageType_MessageType_GetPublicKey     MessageType = 11
	MessageType_MessageType_PublicKey        MessageType = 12
	MessageType_MessageType_SignTx           MessageType = 15
	MessageType_MessageType_TxRequest        MessageType = 21
	MessageType_MessageType_TxAck            MessageType = 22
	MessageType_MessageType_GetAddress       MessageType = 29
	MessageType_MessageType_Address          MessageType = 30
	MessageType_MessageType_SignMessage      MessageType = 38
	MessageType_MessageType_VerifyMessage    MessageType = 39
	MessageType_MessageType_MessageSignature MessageType = 40
	// Crypto
	MessageType_MessageType_CipherKeyValue    MessageType = 23
	MessageType_MessageType_CipheredKeyValue  MessageType = 48
	MessageType_MessageType_SignIdentity      MessageType = 53
	MessageType_MessageType_SignedIdentity    MessageType = 54
	MessageType_MessageType_GetECDHSessionKey MessageType = 61
	MessageType_MessageType_ECDHSessionKey    MessageType = 62
	MessageType_MessageType_CosiCommit        MessageType = 71
	MessageType_MessageType_CosiCommitment    MessageType = 72
	MessageType_MessageType_CosiSign          MessageType = 73
	MessageType_MessageType_CosiSignature     MessageType = 74
	// Debug
	MessageType_MessageType_DebugLinkDecision    MessageType = 100
	MessageType_MessageType_DebugLinkGetState    MessageType = 101
	MessageType_MessageType_DebugLinkState       MessageType = 102
	MessageType_MessageType_DebugLinkStop        MessageType = 103
	MessageType_MessageType_DebugLinkLog         MessageType = 104
	MessageType_MessageType_DebugLinkMemoryRead  MessageType = 110
	MessageType_MessageType_DebugLinkMemory      MessageType = 111
	MessageType_MessageType_DebugLinkMemoryWrite MessageType = 112
	MessageType_MessageType_DebugLinkFlashErase  MessageType = 113
	// Ethereum
	MessageType_MessageType_EthereumGetPublicKey     MessageType = 450
	MessageType_MessageType_EthereumPublicKey        MessageType = 451
	MessageType_MessageType_EthereumGetAddress       MessageType = 56
	MessageType_MessageType_EthereumAddress          MessageType = 57
	MessageType_MessageType_EthereumSignTx           MessageType = 58
	MessageType_MessageType_EthereumTxRequest        MessageType = 59
	MessageType_MessageType_EthereumTxAck            MessageType = 60
	MessageType_MessageType_EthereumSignMessage      MessageType = 64
	MessageType_MessageType_EthereumVerifyMessage    MessageType = 65
	MessageType_MessageType_EthereumMessageSignature MessageType = 66
	// NEM
	MessageType_MessageType_NEMGetAddress       MessageType = 67
	MessageType_MessageType_NEMAddress          MessageType = 68
	MessageType_MessageType_NEMSignTx           MessageType = 69
	MessageType_MessageType_NEMSignedTx         MessageType = 70
	MessageType_MessageType_NEMDecryptMessage   MessageType = 75
	MessageType_MessageType_NEMDecryptedMessage MessageType = 76
	// Lisk
	MessageType_MessageType_LiskGetAddress       MessageType = 114
	MessageType_MessageType_LiskAddress          MessageType = 115
	MessageType_MessageType_LiskSignTx           MessageType = 116
	MessageType_MessageType_LiskSignedTx         MessageType = 117
	MessageType_MessageType_LiskSignMessage      MessageType = 118
	MessageType_MessageType_LiskMessageSignature MessageType = 119
	MessageType_MessageType_LiskVerifyMessage    MessageType = 120
	MessageType_MessageType_LiskGetPublicKey     MessageType = 121
	MessageType_MessageType_LiskPublicKey        MessageType = 122
	// Tezos
	MessageType_MessageType_TezosGetAddress   MessageType = 150
	MessageType_MessageType_TezosAddress      MessageType = 151
	MessageType_MessageType_TezosSignTx       MessageType = 152
	MessageType_MessageType_TezosSignedTx     MessageType = 153
	MessageType_MessageType_TezosGetPublicKey MessageType = 154
	MessageType_MessageType_TezosPublicKey    MessageType = 155
	// Stellar
	MessageType_MessageType_StellarSignTx               MessageType = 202
	MessageType_MessageType_StellarTxOpRequest          MessageType = 203
	MessageType_MessageType_StellarGetAddress           MessageType = 207
	MessageType_MessageType_StellarAddress              MessageType = 208
	MessageType_MessageType_StellarCreateAccountOp      MessageType = 210
	MessageType_MessageType_StellarPaymentOp            MessageType = 211
	MessageType_MessageType_StellarPathPaymentOp        MessageType = 212
	MessageType_MessageType_StellarManageOfferOp        MessageType = 213
	MessageType_MessageType_StellarCreatePassiveOfferOp MessageType = 214
	MessageType_MessageType_StellarSetOptionsOp         MessageType = 215
	MessageType_MessageType_StellarChangeTrustOp        MessageType = 216
	MessageType_MessageType_StellarAllowTrustOp         MessageType = 217
	MessageType_MessageType_StellarAccountMergeOp       MessageType = 218
	// omitted: StellarInflationOp is not a supported operation, would be 219
	MessageType_MessageType_StellarManageDataOp   MessageType = 220
	MessageType_MessageType_StellarBumpSequenceOp MessageType = 221
	MessageType_MessageType_StellarSignedTx       MessageType = 230
	// TRON
	MessageType_MessageType_TronGetAddress MessageType = 250
	MessageType_MessageType_TronAddress    MessageType = 251
	MessageType_MessageType_TronSignTx     MessageType = 252
	MessageType_MessageType_TronSignedTx   MessageType = 253
	// Cardano
	// dropped Sign/VerifyMessage ids 300-302
	MessageType_MessageType_CardanoSignTx       MessageType = 303
	MessageType_MessageType_CardanoTxRequest    MessageType = 304
	MessageType_MessageType_CardanoGetPublicKey MessageType = 305
	MessageType_MessageType_CardanoPublicKey    MessageType = 306
	MessageType_MessageType_CardanoGetAddress   MessageType = 307
	MessageType_MessageType_CardanoAddress      MessageType = 308
	MessageType_MessageType_CardanoTxAck        MessageType = 309
	MessageType_MessageType_CardanoSignedTx     MessageType = 310
	// Ontology
	MessageType_MessageType_OntologyGetAddress               MessageType = 350
	MessageType_MessageType_OntologyAddress                  MessageType = 351
	MessageType_MessageType_OntologyGetPublicKey             MessageType = 352
	MessageType_MessageType_OntologyPublicKey                MessageType = 353
	MessageType_MessageType_OntologySignTransfer             MessageType = 354
	MessageType_MessageType_OntologySignedTransfer           MessageType = 355
	MessageType_MessageType_OntologySignWithdrawOng          MessageType = 356
	MessageType_MessageType_OntologySignedWithdrawOng        MessageType = 357
	MessageType_MessageType_OntologySignOntIdRegister        MessageType = 358
	MessageType_MessageType_OntologySignedOntIdRegister      MessageType = 359
	MessageType_MessageType_OntologySignOntIdAddAttributes   MessageType = 360
	MessageType_MessageType_OntologySignedOntIdAddAttributes MessageType = 361
	// Ripple
	MessageType_MessageType_RippleGetAddress MessageType = 400
	MessageType_MessageType_RippleAddress    MessageType = 401
	MessageType_MessageType_RippleSignTx     MessageType = 402
	MessageType_MessageType_RippleSignedTx   MessageType = 403
	// Monero
	MessageType_MessageType_MoneroTransactionInitRequest              MessageType = 501
	MessageType_MessageType_MoneroTransactionInitAck                  MessageType = 502
	MessageType_MessageType_MoneroTransactionSetInputRequest          MessageType = 503
	MessageType_MessageType_MoneroTransactionSetInputAck              MessageType = 504
	MessageType_MessageType_MoneroTransactionInputsPermutationRequest MessageType = 505
	MessageType_MessageType_MoneroTransactionInputsPermutationAck     MessageType = 506
	MessageType_MessageType_MoneroTransactionInputViniRequest         MessageType = 507
	MessageType_MessageType_MoneroTransactionInputViniAck             MessageType = 508
	MessageType_MessageType_MoneroTransactionAllInputsSetRequest      MessageType = 509
	MessageType_MessageType_MoneroTransactionAllInputsSetAck          MessageType = 510
	MessageType_MessageType_MoneroTransactionSetOutputRequest         MessageType = 511
	MessageType_MessageType_MoneroTransactionSetOutputAck             MessageType = 512
	MessageType_MessageType_MoneroTransactionAllOutSetRequest         MessageType = 513
	MessageType_MessageType_MoneroTransactionAllOutSetAck             MessageType = 514
	MessageType_MessageType_MoneroTransactionSignInputRequest         MessageType = 515
	MessageType_MessageType_MoneroTransactionSignInputAck             MessageType = 516
	MessageType_MessageType_MoneroTransactionFinalRequest             MessageType = 517
	MessageType_MessageType_MoneroTransactionFinalAck                 MessageType = 518
	MessageType_MessageType_MoneroKeyImageExportInitRequest           MessageType = 530
	MessageType_MessageType_MoneroKeyImageExportInitAck               MessageType = 531
	MessageType_MessageType_MoneroKeyImageSyncStepRequest             MessageType = 532
	MessageType_MessageType_MoneroKeyImageSyncStepAck                 MessageType = 533
	MessageType_MessageType_MoneroKeyImageSyncFinalRequest            MessageType = 534
	MessageType_MessageType_MoneroKeyImageSyncFinalAck                MessageType = 535
	MessageType_MessageType_MoneroGetAddress                          MessageType = 540
	MessageType_MessageType_MoneroAddress                             MessageType = 541
	MessageType_MessageType_MoneroGetWatchKey                         MessageType = 542
	MessageType_MessageType_MoneroWatchKey                            MessageType = 543
	MessageType_MessageType_DebugMoneroDiagRequest                    MessageType = 546
	MessageType_MessageType_DebugMoneroDiagAck                        MessageType = 547
	MessageType_MessageType_MoneroGetTxKeyRequest                     MessageType = 550
	MessageType_MessageType_MoneroGetTxKeyAck                         MessageType = 551
	MessageType_MessageType_MoneroLiveRefreshStartRequest             MessageType = 552
	MessageType_MessageType_MoneroLiveRefreshStartAck                 MessageType = 553
	MessageType_MessageType_MoneroLiveRefreshStepRequest              MessageType = 554
	MessageType_MessageType_MoneroLiveRefreshStepAck                  MessageType = 555
	MessageType_MessageType_MoneroLiveRefreshFinalRequest             MessageType = 556
	MessageType_MessageType_MoneroLiveRefreshFinalAck                 MessageType = 557
	// EOS
	MessageType_MessageType_EosGetPublicKey    MessageType = 600
	MessageType_MessageType_EosPublicKey       MessageType = 601
	MessageType_MessageType_EosSignTx          MessageType = 602
	MessageType_MessageType_EosTxActionRequest MessageType = 603
	MessageType_MessageType_EosTxActionAck     MessageType = 604
	MessageType_MessageType_EosSignedTx        MessageType = 605
)

var MessageType_name = map[int32]string{
	0:   "MessageType_Initialize",
	1:   "MessageType_Ping",
	2:   "MessageType_Success",
	3:   "MessageType_Failure",
	4:   "MessageType_ChangePin",
	5:   "MessageType_WipeDevice",
	9:   "MessageType_GetEntropy",
	10:  "MessageType_Entropy",
	13:  "MessageType_LoadDevice",
	14:  "MessageType_ResetDevice",
	17:  "MessageType_Features",
	18:  "MessageType_PinMatrixRequest",
	19:  "MessageType_PinMatrixAck",
	20:  "MessageType_Cancel",
	24:  "MessageType_ClearSession",
	25:  "MessageType_ApplySettings",
	26:  "MessageType_ButtonRequest",
	27:  "MessageType_ButtonAck",
	28:  "MessageType_ApplyFlags",
	34:  "MessageType_BackupDevice",
	35:  "MessageType_EntropyRequest",
	36:  "MessageType_EntropyAck",
	41:  "MessageType_PassphraseRequest",
	42:  "MessageType_PassphraseAck",
	77:  "MessageType_PassphraseStateRequest",
	78:  "MessageType_PassphraseStateAck",
	45:  "MessageType_RecoveryDevice",
	46:  "MessageType_WordRequest",
	47:  "MessageType_WordAck",
	55:  "MessageType_GetFeatures",
	63:  "MessageType_SetU2FCounter",
	6:   "MessageType_FirmwareErase",
	7:   "MessageType_FirmwareUpload",
	8:   "MessageType_FirmwareRequest",
	32:  "MessageType_SelfTest",
	11:  "MessageType_GetPublicKey",
	12:  "MessageType_PublicKey",
	15:  "MessageType_SignTx",
	21:  "MessageType_TxRequest",
	22:  "MessageType_TxAck",
	29:  "MessageType_GetAddress",
	30:  "MessageType_Address",
	38:  "MessageType_SignMessage",
	39:  "MessageType_VerifyMessage",
	40:  "MessageType_MessageSignature",
	23:  "MessageType_CipherKeyValue",
	48:  "MessageType_CipheredKeyValue",
	53:  "MessageType_SignIdentity",
	54:  "MessageType_SignedIdentity",
	61:  "MessageType_GetECDHSessionKey",
	62:  "MessageType_ECDHSessionKey",
	71:  "MessageType_CosiCommit",
	72:  "MessageType_CosiCommitment",
	73:  "MessageType_CosiSign",
	74:  "MessageType_CosiSignature",
	100: "MessageType_DebugLinkDecision",
	101: "MessageType_DebugLinkGetState",
	102: "MessageType_DebugLinkState",
	103: "MessageType_DebugLinkStop",
	104: "MessageType_DebugLinkLog",
	110: "MessageType_DebugLinkMemoryRead",
	111: "MessageType_DebugLinkMemory",
	112: "MessageType_DebugLinkMemoryWrite",
	113: "MessageType_DebugLinkFlashErase",
	450: "MessageType_EthereumGetPublicKey",
	451: "MessageType_EthereumPublicKey",
	56:  "MessageType_EthereumGetAddress",
	57:  "MessageType_EthereumAddress",
	58:  "MessageType_EthereumSignTx",
	59:  "MessageType_EthereumTxRequest",
	60:  "MessageType_EthereumTxAck",
	64:  "MessageType_EthereumSignMessage",
	65:  "MessageType_EthereumVerifyMessage",
	66:  "MessageType_EthereumMessageSignature",
	67:  "MessageType_NEMGetAddress",
	68:  "MessageType_NEMAddress",
	69:  "MessageType_NEMSignTx",
	70:  "MessageType_NEMSignedTx",
	75:  "MessageType_NEMDecryptMessage",
	76:  "MessageType_NEMDecryptedMessage",
	114: "MessageType_LiskGetAddress",
	115: "MessageType_LiskAddress",
	116: "MessageType_LiskSignTx",
	117: "MessageType_LiskSignedTx",
	118: "MessageType_LiskSignMessage",
	119: "MessageType_LiskMessageSignature",
	120: "MessageType_LiskVerifyMessage",
	121: "MessageType_LiskGetPublicKey",
	122: "MessageType_LiskPublicKey",
	150: "MessageType_TezosGetAddress",
	151: "MessageType_TezosAddress",
	152: "MessageType_TezosSignTx",
	153: "MessageType_TezosSignedTx",
	154: "MessageType_TezosGetPublicKey",
	155: "MessageType_TezosPublicKey",
	202: "MessageType_StellarSignTx",
	203: "MessageType_StellarTxOpRequest",
	207: "MessageType_StellarGetAddress",
	208: "MessageType_StellarAddress",
	210: "MessageType_StellarCreateAccountOp",
	211: "MessageType_StellarPaymentOp",
	212: "MessageType_StellarPathPaymentOp",
	213: "MessageType_StellarManageOfferOp",
	214: "MessageType_StellarCreatePassiveOfferOp",
	215: "MessageType_StellarSetOptionsOp",
	216: "MessageType_StellarChangeTrustOp",
	217: "MessageType_StellarAllowTrustOp",
	218: "MessageType_StellarAccountMergeOp",
	220: "MessageType_StellarManageDataOp",
	221: "MessageType_StellarBumpSequenceOp",
	230: "MessageType_StellarSignedTx",
	250: "MessageType_TronGetAddress",
	251: "MessageType_TronAddress",
	252: "MessageType_TronSignTx",
	253: "MessageType_TronSignedTx",
	303: "MessageType_CardanoSignTx",
	304: "MessageType_CardanoTxRequest",
	305: "MessageType_CardanoGetPublicKey",
	306: "MessageType_CardanoPublicKey",
	307: "MessageType_CardanoGetAddress",
	308: "MessageType_CardanoAddress",
	309: "MessageType_CardanoTxAck",
	310: "MessageType_CardanoSignedTx",
	350: "MessageType_OntologyGetAddress",
	351: "MessageType_OntologyAddress",
	352: "MessageType_OntologyGetPublicKey",
	353: "MessageType_OntologyPublicKey",
	354: "MessageType_OntologySignTransfer",
	355: "MessageType_OntologySignedTransfer",
	356: "MessageType_OntologySignWithdrawOng",
	357: "MessageType_OntologySignedWithdrawOng",
	358: "MessageType_OntologySignOntIdRegister",
	359: "MessageType_OntologySignedOntIdRegister",
	360: "MessageType_OntologySignOntIdAddAttributes",
	361: "MessageType_OntologySignedOntIdAddAttributes",
	400: "MessageType_RippleGetAddress",
	401: "MessageType_RippleAddress",
	402: "MessageType_RippleSignTx",
	403: "MessageType_RippleSignedTx",
	501: "MessageType_MoneroTransactionInitRequest",
	502: "MessageType_MoneroTransactionInitAck",
	503: "MessageType_MoneroTransactionSetInputRequest",
	504: "MessageType_MoneroTransactionSetInputAck",
	505: "MessageType_MoneroTransactionInputsPermutationRequest",
	506: "MessageType_MoneroTransactionInputsPermutationAck",
	507: "MessageType_MoneroTransactionInputViniRequest",
	508: "MessageType_MoneroTransactionInputViniAck",
	509: "MessageType_MoneroTransactionAllInputsSetRequest",
	510: "MessageType_MoneroTransactionAllInputsSetAck",
	511: "MessageType_MoneroTransactionSetOutputRequest",
	512: "MessageType_MoneroTransactionSetOutputAck",
	513: "MessageType_MoneroTransactionAllOutSetRequest",
	514: "MessageType_MoneroTransactionAllOutSetAck",
	515: "MessageType_MoneroTransactionSignInputRequest",
	516: "MessageType_MoneroTransactionSignInputAck",
	517: "MessageType_MoneroTransactionFinalRequest",
	518: "MessageType_MoneroTransactionFinalAck",
	530: "MessageType_MoneroKeyImageExportInitRequest",
	531: "MessageType_MoneroKeyImageExportInitAck",
	532: "MessageType_MoneroKeyImageSyncStepRequest",
	533: "MessageType_MoneroKeyImageSyncStepAck",
	534: "MessageType_MoneroKeyImageSyncFinalRequest",
	535: "MessageType_MoneroKeyImageSyncFinalAck",
	540: "MessageType_MoneroGetAddress",
	541: "MessageType_MoneroAddress",
	542: "MessageType_MoneroGetWatchKey",
	543: "MessageType_MoneroWatchKey",
	546: "MessageType_DebugMoneroDiagRequest",
	547: "MessageType_DebugMoneroDiagAck",
	550: "MessageType_MoneroGetTxKeyRequest",
	551: "MessageType_MoneroGetTxKeyAck",
	552: "MessageType_MoneroLiveRefreshStartRequest",
	553: "MessageType_MoneroLiveRefreshStartAck",
	554: "MessageType_MoneroLiveRefreshStepRequest",
	555: "MessageType_MoneroLiveRefreshStepAck",
	556: "MessageType_MoneroLiveRefreshFinalRequest",
	557: "MessageType_MoneroLiveRefreshFinalAck",
	600: "MessageType_EosGetPublicKey",
	601: "MessageType_EosPublicKey",
	602: "MessageType_EosSignTx",
	603: "MessageType_EosTxActionRequest",
	604: "MessageType_EosTxActionAck",
	605: "MessageType_EosSignedTx",
}
var MessageType_value = map[string]int32{
	"MessageType_Initialize":                                0,
	"MessageType_Ping":                                      1,
	"MessageType_Success":                                   2,
	"MessageType_Failure":                                   3,
	"MessageType_ChangePin":                                 4,
	"MessageType_WipeDevice":                                5,
	"MessageType_GetEntropy":                                9,
	"MessageType_Entropy":                                   10,
	"MessageType_LoadDevice":                                13,
	"MessageType_ResetDevice":                               14,
	"MessageType_Features":                                  17,
	"MessageType_PinMatrixRequest":                          18,
	"MessageType_PinMatrixAck":                              19,
	"MessageType_Cancel":                                    20,
	"MessageType_ClearSession":                              24,
	"MessageType_ApplySettings":                             25,
	"MessageType_ButtonRequest":                             26,
	"MessageType_ButtonAck":                                 27,
	"MessageType_ApplyFlags":                                28,
	"MessageType_BackupDevice":                              34,
	"MessageType_EntropyRequest":                            35,
	"MessageType_EntropyAck":                                36,
	"MessageType_PassphraseRequest":                         41,
	"MessageType_PassphraseAck":                             42,
	"MessageType_PassphraseStateRequest":                    77,
	"MessageType_PassphraseStateAck":                        78,
	"MessageType_RecoveryDevice":                            45,
	"MessageType_WordRequest":                               46,
	"MessageType_WordAck":                                   47,
	"MessageType_GetFeatures":                               55,
	"MessageType_SetU2FCounter":                             63,
	"MessageType_FirmwareErase":                             6,
	"MessageType_FirmwareUpload":                            7,
	"MessageType_FirmwareRequest":                           8,
	"MessageType_SelfTest":                                  32,
	"MessageType_GetPublicKey":                              11,
	"MessageType_PublicKey":                                 12,
	"MessageType_SignTx":                                    15,
	"MessageType_TxRequest":                                 21,
	"MessageType_TxAck":                                     22,
	"MessageType_GetAddress":                                29,
	"MessageType_Address":                                   30,
	"MessageType_SignMessage":                               38,
	"MessageType_VerifyMessage":                             39,
	"MessageType_MessageSignature":                          40,
	"MessageType_CipherKeyValue":                            23,
	"MessageType_CipheredKeyValue":                          48,
	"MessageType_SignIdentity":                              53,
	"MessageType_SignedIdentity":                            54,
	"MessageType_GetECDHSessionKey":                         61,
	"MessageType_ECDHSessionKey":                            62,
	"MessageType_CosiCommit":                                71,
	"MessageType_CosiCommitment":                            72,
	"MessageType_CosiSign":                                  73,
	"MessageType_CosiSignature":                             74,
	"MessageType_DebugLinkDecision":                         100,
	"MessageType_DebugLinkGetState":                         101,
	"MessageType_DebugLinkState":                            102,
	"MessageType_DebugLinkStop":                             103,
	"MessageType_DebugLinkLog":                              104,
	"MessageType_DebugLinkMemoryRead":                       110,
	"MessageType_DebugLinkMemory":                           111,
	"MessageType_DebugLinkMemoryWrite":                      112,
	"MessageType_DebugLinkFlashErase":                       113,
	"MessageType_EthereumGetPublicKey":                      450,
	"MessageType_EthereumPublicKey":                         451,
	"MessageType_EthereumGetAddress":                        56,
	"MessageType_EthereumAddress":                           57,
	"MessageType_EthereumSignTx":                            58,
	"MessageType_EthereumTxRequest":                         59,
	"MessageType_EthereumTxAck":                             60,
	"MessageType_EthereumSignMessage":                       64,
	"MessageType_EthereumVerifyMessage":                     65,
	"MessageType_EthereumMessageSignature":                  66,
	"MessageType_NEMGetAddress":                             67,
	"MessageType_NEMAddress":                                68,
	"MessageType_NEMSignTx":                                 69,
	"MessageType_NEMSignedTx":                               70,
	"MessageType_NEMDecryptMessage":                         75,
	"MessageType_NEMDecryptedMessage":                       76,
	"MessageType_LiskGetAddress":                            114,
	"MessageType_LiskAddress":                               115,
	"MessageType_LiskSignTx":                                116,
	"MessageType_LiskSignedTx":                              117,
	"MessageType_LiskSignMessage":                           118,
	"MessageType_LiskMessageSignature":                      119,
	"MessageType_LiskVerifyMessage":                         120,
	"MessageType_LiskGetPublicKey":                          121,
	"MessageType_LiskPublicKey":                             122,
	"MessageType_TezosGetAddress":                           150,
	"MessageType_TezosAddress":                              151,
	"MessageType_TezosSignTx":                               152,
	"MessageType_TezosSignedTx":                             153,
	"MessageType_TezosGetPublicKey":                         154,
	"MessageType_TezosPublicKey":                            155,
	"MessageType_StellarSignTx":                             202,
	"MessageType_StellarTxOpRequest":                        203,
	"MessageType_StellarGetAddress":                         207,
	"MessageType_StellarAddress":                            208,
	"MessageType_StellarCreateAccountOp":                    210,
	"MessageType_StellarPaymentOp":                          211,
	"MessageType_StellarPathPaymentOp":                      212,
	"MessageType_StellarManageOfferOp":                      213,
	"MessageType_StellarCreatePassiveOfferOp":               214,
	"MessageType_StellarSetOptionsOp":                       215,
	"MessageType_StellarChangeTrustOp":                      216,
	"MessageType_StellarAllowTrustOp":                       217,
	"MessageType_StellarAccountMergeOp":                     218,
	"MessageType_StellarManageDataOp":                       220,
	"MessageType_StellarBumpSequenceOp":                     221,
	"MessageType_StellarSignedTx":                           230,
	"MessageType_TronGetAddress":                            250,
	"MessageType_TronAddress":                               251,
	"MessageType_TronSignTx":                                252,
	"MessageType_TronSignedTx":                              253,
	"MessageType_CardanoSignTx":                             303,
	"MessageType_CardanoTxRequest":                          304,
	"MessageType_CardanoGetPublicKey":                       305,
	"MessageType_CardanoPublicKey":                          306,
	"MessageType_CardanoGetAddress":                         307,
	"MessageType_CardanoAddress":                            308,
	"MessageType_CardanoTxAck":                              309,
	"MessageType_CardanoSignedTx":                           310,
	"MessageType_OntologyGetAddress":                        350,
	"MessageType_OntologyAddress":                           351,
	"MessageType_OntologyGetPublicKey":                      352,
	"MessageType_OntologyPublicKey":                         353,
	"MessageType_OntologySignTransfer":                      354,
	"MessageType_OntologySignedTransfer":                    355,
	"MessageType_OntologySignWithdrawOng":                   356,
	"MessageType_OntologySignedWithdrawOng":                 357,
	"MessageType_OntologySignOntIdRegister":                 358,
	"MessageType_OntologySignedOntIdRegister":               359,
	"MessageType_OntologySignOntIdAddAttributes":            360,
	"MessageType_OntologySignedOntIdAddAttributes":          361,
	"MessageType_RippleGetAddress":                          400,
	"MessageType_RippleAddress":                             401,
	"MessageType_RippleSignTx":                              402,
	"MessageType_RippleSignedTx":                            403,
	"MessageType_MoneroTransactionInitRequest":              501,
	"MessageType_MoneroTransactionInitAck":                  502,
	"MessageType_MoneroTransactionSetInputRequest":          503,
	"MessageType_MoneroTransactionSetInputAck":              504,
	"MessageType_MoneroTransactionInputsPermutationRequest": 505,
	"MessageType_MoneroTransactionInputsPermutationAck":     506,
	"MessageType_MoneroTransactionInputViniRequest":         507,
	"MessageType_MoneroTransactionInputViniAck":             508,
	"MessageType_MoneroTransactionAllInputsSetRequest":      509,
	"MessageType_MoneroTransactionAllInputsSetAck":          510,
	"MessageType_MoneroTransactionSetOutputRequest":         511,
	"MessageType_MoneroTransactionSetOutputAck":             512,
	"MessageType_MoneroTransactionAllOutSetRequest":         513,
	"MessageType_MoneroTransactionAllOutSetAck":             514,
	"MessageType_MoneroTransactionSignInputRequest":         515,
	"MessageType_MoneroTransactionSignInputAck":             516,
	"MessageType_MoneroTransactionFinalRequest":             517,
	"MessageType_MoneroTransactionFinalAck":                 518,
	"MessageType_MoneroKeyImageExportInitRequest":           530,
	"MessageType_MoneroKeyImageExportInitAck":               531,
	"MessageType_MoneroKeyImageSyncStepRequest":             532,
	"MessageType_MoneroKeyImageSyncStepAck":                 533,
	"MessageType_MoneroKeyImageSyncFinalRequest":            534,
	"MessageType_MoneroKeyImageSyncFinalAck":                535,
	"MessageType_MoneroGetAddress":                          540,
	"MessageType_MoneroAddress":                             541,
	"MessageType_MoneroGetWatchKey":                         542,
	"MessageType_MoneroWatchKey":                            543,
	"MessageType_DebugMoneroDiagRequest":                    546,
	"MessageType_DebugMoneroDiagAck":                        547,
	"MessageType_MoneroGetTxKeyRequest":                     550,
	"MessageType_MoneroGetTxKeyAck":                         551,
	"MessageType_MoneroLiveRefreshStartRequest":             552,
	"MessageType_MoneroLiveRefreshStartAck":                 553,
	"MessageType_MoneroLiveRefreshStepRequest":              554,
	"MessageType_MoneroLiveRefreshStepAck":                  555,
	"MessageType_MoneroLiveRefreshFinalRequest":             556,
	"MessageType_MoneroLiveRefreshFinalAck":                 557,
	"MessageType_EosGetPublicKey":                           600,
	"MessageType_EosPublicKey":                              601,
	"MessageType_EosSignTx":                                 602,
	"MessageType_EosTxActionRequest":                        603,
	"MessageType_EosTxActionAck":                            604,
	"MessageType_EosSignedTx":                               605,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

var E_WireIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "hw.trezor.messages.wire_in",
	Tag:           "varint,50002,opt,name=wire_in,json=wireIn",
	Filename:      "messages.proto",
}

var E_WireOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "hw.trezor.messages.wire_out",
	Tag:           "varint,50003,opt,name=wire_out,json=wireOut",
	Filename:      "messages.proto",
}

var E_WireDebugIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50004,
	Name:          "hw.trezor.messages.wire_debug_in",
	Tag:           "varint,50004,opt,name=wire_debug_in,json=wireDebugIn",
	Filename:      "messages.proto",
}

var E_WireDebugOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50005,
	Name:          "hw.trezor.messages.wire_debug_out",
	Tag:           "varint,50005,opt,name=wire_debug_out,json=wireDebugOut",
	Filename:      "messages.proto",
}

var E_WireTiny = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50006,
	Name:          "hw.trezor.messages.wire_tiny",
	Tag:           "varint,50006,opt,name=wire_tiny,json=wireTiny",
	Filename:      "messages.proto",
}

var E_WireBootloader = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50007,
	Name:          "hw.trezor.messages.wire_bootloader",
	Tag:           "varint,50007,opt,name=wire_bootloader,json=wireBootloader",
	Filename:      "messages.proto",
}

var E_WireNoFsm = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50008,
	Name:          "hw.trezor.messages.wire_no_fsm",
	Tag:           "varint,50008,opt,name=wire_no_fsm,json=wireNoFsm",
	Filename:      "messages.proto",
}

func init() {
	proto.RegisterEnum("hw.trezor.messages.MessageType", MessageType_name, MessageType_value)
	proto.RegisterExtension(E_WireIn)
	proto.RegisterExtension(E_WireOut)
	proto.RegisterExtension(E_WireDebugIn)
	proto.RegisterExtension(E_WireDebugOut)
	proto.RegisterExtension(E_WireTiny)
	proto.RegisterExtension(E_WireBootloader)
	proto.RegisterExtension(E_WireNoFsm)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x9a, 0x49, 0x73, 0x1b, 0xc7,
	0x15, 0xc7, 0x03, 0x70, 0x62, 0xd3, 0xad, 0xc5, 0x6d, 0xda, 0x92, 0x28, 0x68, 0xa3, 0x16, 0x4b,
	0xd4, 0x06, 0xc9, 0x8e, 0x65, 0x3b, 0xb4, 0xe2, 0x88, 0x04, 0x41, 0x1a, 0x21, 0x41, 0xb0, 0x08,
	0x58, 0x3c, 0xaa, 0x86, 0x98, 0x47, 0xa0, 0x8b, 0x83, 0x99, 0x71, 0x4f, 0x0f, 0x49, 0xe8, 0x94,
	0xd5, 0x67, 0xc7, 0x4e, 0x6c, 0x65, 0x57, 0x25, 0x55, 0x89, 0xb3, 0x55, 0x9c, 0x45, 0xa9, 0x1c,
	0x53, 0xc9, 0x2d, 0x39, 0x24, 0xe5, 0x55, 0x76, 0xec, 0xec, 0x71, 0x92, 0x0f, 0x90, 0xcd, 0x4b,
	0x92, 0xea, 0x99, 0xee, 0xc6, 0xcc, 0xa0, 0x01, 0xc2, 0x37, 0x91, 0xf3, 0x7b, 0xff, 0xb7, 0xf4,
	0xeb, 0xd7, 0x3d, 0x43, 0xa1, 0x9d, 0x2d, 0xf0, 0x7d, 0xb3, 0x01, 0x7e, 0xde, 0xa3, 0x2e, 0x73,
	0x47, 0x46, 0x9a, 0x1b, 0x79, 0x46, 0xe1, 0xaa, 0x4b, 0xf3, 0xf2, 0x49, 0x6e, 0xac, 0xe1, 0xba,
	0x0d, 0x1b, 0xce, 0x85, 0xc4, 0x4a, 0xb0, 0x7a, 0xce, 0x02, 0xbf, 0x4e, 0x89, 0xc7, 0x5c, 0x1a,
	0x59, 0x9d, 0xba, 0x7e, 0x11, 0x6d, 0x2b, 0x47, 0x78, 0xad, 0xed, 0xc1, 0xc8, 0x31, 0xb4, 0x3b,
	0xf6, 0xe3, 0x95, 0x92, 0x43, 0x18, 0x31, 0x6d, 0x72, 0x15, 0xf0, 0xfb, 0x72, 0xc3, 0x4f, 0xdc,
	0x18, 0xcd, 0x3c, 0x77, 0x63, 0x34, 0x33, 0x92, 0x43, 0x38, 0x4e, 0x2d, 0x12, 0xa7, 0x81, 0x33,
	0x39, 0x83, 0x3f, 0x1f, 0x39, 0x80, 0xee, 0x8c, 0x3f, 0xab, 0x06, 0xf5, 0x3a, 0xf8, 0x3e, 0xce,
	0xe6, 0x8c, 0x6b, 0x9a, 0xc7, 0x33, 0x26, 0xb1, 0x03, 0x0a, 0x78, 0x48, 0x3c, 0x3e, 0x84, 0x76,
	0xc5, 0x1f, 0x17, 0x9a, 0xa6, 0xd3, 0x80, 0x45, 0xe2, 0x60, 0x43, 0xc8, 0x8f, 0x25, 0x03, 0x5c,
	0x26, 0x1e, 0x4c, 0xc3, 0x3a, 0xa9, 0x03, 0x7e, 0xbf, 0x9e, 0x98, 0x05, 0x56, 0x74, 0x18, 0x75,
	0xbd, 0x36, 0xbe, 0x4d, 0x1f, 0xa2, 0x7c, 0x8c, 0x44, 0x0c, 0x29, 0x81, 0x79, 0xd7, 0xb4, 0x84,
	0x8b, 0x1d, 0x42, 0xe0, 0x30, 0xda, 0x13, 0x27, 0x96, 0xc0, 0x07, 0x26, 0x90, 0x9d, 0x02, 0x39,
	0x88, 0xee, 0x4a, 0xe4, 0x09, 0x26, 0x0b, 0x28, 0xf8, 0xf8, 0x0e, 0xe1, 0xe4, 0x38, 0xda, 0x9f,
	0x2a, 0x61, 0xd9, 0x64, 0x94, 0x6c, 0x2e, 0xc1, 0x63, 0x01, 0xf8, 0x0c, 0x8f, 0x08, 0xee, 0x14,
	0x1a, 0xd5, 0x72, 0x93, 0xf5, 0x35, 0x7c, 0x67, 0x6e, 0xbb, 0x5c, 0x92, 0x9f, 0x46, 0x81, 0x8f,
	0x24, 0x8a, 0x67, 0x3a, 0x75, 0xb0, 0xf1, 0x5d, 0xb1, 0x85, 0x3b, 0x92, 0x54, 0x2b, 0xd8, 0x60,
	0xd2, 0x2a, 0xf8, 0x3e, 0x71, 0x1d, 0x3c, 0x2a, 0x22, 0x3f, 0x8a, 0xf6, 0xc6, 0x99, 0x49, 0xcf,
	0xb3, 0xdb, 0x55, 0x60, 0x8c, 0x38, 0x0d, 0x1f, 0xef, 0xd5, 0x43, 0x53, 0x01, 0x63, 0xae, 0x23,
	0x63, 0xcf, 0x89, 0xd8, 0x4f, 0x24, 0x17, 0x33, 0x82, 0x78, 0xe0, 0xfb, 0xba, 0x02, 0xdf, 0xdd,
	0xe5, 0x72, 0xc6, 0x36, 0x1b, 0x3e, 0xde, 0x2f, 0xfc, 0xa5, 0x02, 0x9f, 0x32, 0xeb, 0x6b, 0x81,
	0x27, 0x4a, 0x7e, 0x44, 0x30, 0xc7, 0x50, 0x4e, 0xb3, 0xac, 0x32, 0xa8, 0xa3, 0xfa, 0xd5, 0x15,
	0x14, 0x8f, 0xea, 0x98, 0xd0, 0x39, 0x81, 0x0e, 0x24, 0x4a, 0x6e, 0xfa, 0xbe, 0xd7, 0xa4, 0xa6,
	0x0f, 0x52, 0xea, 0xa4, 0x90, 0x3a, 0x9d, 0x2c, 0x42, 0x07, 0xe4, 0x6a, 0xa7, 0x52, 0x39, 0x9e,
	0x41, 0x47, 0xf4, 0x70, 0x95, 0x99, 0x4c, 0x49, 0x97, 0x85, 0xf4, 0x79, 0x74, 0xb0, 0x0f, 0xcd,
	0xf5, 0x17, 0x52, 0xfa, 0xa9, 0xec, 0x97, 0xa0, 0xee, 0xae, 0x03, 0x6d, 0x8b, 0x1a, 0x9d, 0xd5,
	0x77, 0xee, 0xb2, 0x4b, 0x2d, 0xe9, 0x3a, 0xaf, 0xdf, 0xa1, 0x1c, 0xe1, 0xfe, 0xce, 0xe9, 0x15,
	0x66, 0x81, 0xa9, 0xde, 0x7e, 0x40, 0xdf, 0x1c, 0x55, 0x60, 0x8f, 0xde, 0x3b, 0x53, 0x70, 0x03,
	0x87, 0x01, 0xc5, 0x1f, 0x56, 0x55, 0x4e, 0x40, 0x33, 0x84, 0xb6, 0x36, 0x4c, 0x0a, 0x45, 0x9e,
	0x24, 0xbe, 0x25, 0xea, 0xd9, 0x9f, 0x70, 0x70, 0x3c, 0x99, 0x98, 0x04, 0x1f, 0xf5, 0x6c, 0xd7,
	0xb4, 0xf0, 0xad, 0x31, 0xf2, 0x24, 0xda, 0xa7, 0x23, 0x65, 0x82, 0xc3, 0xb9, 0xe1, 0x6b, 0x12,
	0x3d, 0x92, 0xdc, 0x9e, 0x55, 0xb0, 0x57, 0x6b, 0x9c, 0x19, 0x8b, 0xc9, 0xa5, 0x7a, 0x6e, 0x16,
	0xd8, 0x62, 0xb0, 0x62, 0x93, 0xfa, 0x1c, 0xb4, 0xf1, 0x36, 0x91, 0x45, 0x6a, 0x5e, 0x75, 0x80,
	0xed, 0xa2, 0x9a, 0xfb, 0x93, 0x7b, 0xb2, 0x4a, 0x1a, 0x4e, 0x6d, 0x13, 0xdf, 0xae, 0x37, 0xaf,
	0xa9, 0xed, 0xbf, 0x4b, 0x98, 0xef, 0x43, 0x77, 0x24, 0x01, 0xbe, 0x14, 0xbb, 0x7b, 0x4e, 0xba,
	0x49, 0xcb, 0xa2, 0x7c, 0xda, 0x1e, 0xd0, 0x4f, 0x3a, 0xf9, 0xf8, 0xa0, 0x50, 0x4f, 0xad, 0x25,
	0x0f, 0x4e, 0xfc, 0x8c, 0x8f, 0xeb, 0xd7, 0xf2, 0x32, 0x50, 0xb2, 0xda, 0x96, 0xd0, 0x09, 0x01,
	0xa5, 0x86, 0x99, 0xf8, 0x37, 0x97, 0x0b, 0x3b, 0x03, 0x8f, 0x0b, 0x7f, 0xa9, 0x1e, 0x2d, 0x10,
	0xaf, 0x09, 0x74, 0x0e, 0xda, 0x97, 0x4d, 0x3b, 0x00, 0xbc, 0x47, 0xaf, 0x16, 0x51, 0x60, 0x29,
	0xee, 0xbc, 0x50, 0x4b, 0xad, 0x0f, 0x77, 0x57, 0xb2, 0xc0, 0x61, 0x84, 0xb5, 0xf1, 0x05, 0xfd,
	0x4c, 0xe0, 0x0c, 0x58, 0x8a, 0xba, 0x5f, 0x0d, 0xaa, 0x03, 0xe9, 0x23, 0xa3, 0x30, 0xfd, 0x88,
	0x18, 0x8c, 0x7c, 0x35, 0x3f, 0xd4, 0x63, 0xc4, 0x24, 0xa9, 0x87, 0xf5, 0x23, 0xa6, 0xe0, 0xfa,
	0xa4, 0xe0, 0xb6, 0x5a, 0x84, 0xe1, 0x59, 0xbd, 0x4e, 0x87, 0x68, 0x81, 0xc3, 0xf0, 0x23, 0x42,
	0x27, 0x75, 0x86, 0x70, 0x8a, 0x27, 0x80, 0x4b, 0xfa, 0xb5, 0x91, 0xcf, 0xa3, 0x9a, 0x7f, 0x44,
	0x88, 0x9c, 0x4b, 0xe6, 0x36, 0x0d, 0x2b, 0x41, 0x63, 0x9e, 0x38, 0x6b, 0xd3, 0x50, 0x27, 0xe1,
	0xdc, 0xb7, 0x72, 0xdb, 0xaf, 0xc7, 0x07, 0xc9, 0xe9, 0x1e, 0x06, 0xb3, 0xc0, 0xc2, 0xe1, 0x83,
	0x21, 0x37, 0x2c, 0x0d, 0xd2, 0x89, 0x28, 0x38, 0x22, 0x57, 0x73, 0xc6, 0xb3, 0x9a, 0x40, 0x63,
	0x94, 0xeb, 0xe1, 0x46, 0xce, 0xb8, 0xae, 0x59, 0x4e, 0x05, 0xcd, 0xbb, 0x0d, 0xdc, 0x14, 0x42,
	0x27, 0xd1, 0x21, 0x2d, 0x53, 0x86, 0x96, 0x4b, 0xdb, 0x4b, 0x60, 0x5a, 0xd8, 0x11, 0x72, 0x77,
	0x27, 0x87, 0x41, 0x0a, 0xc5, 0xae, 0x50, 0x3c, 0x85, 0xc6, 0xfa, 0x60, 0xcb, 0x94, 0x30, 0xc0,
	0x9e, 0x90, 0xec, 0xe5, 0x7d, 0xc6, 0x36, 0xfd, 0x66, 0x34, 0xb8, 0x1e, 0x13, 0xe8, 0xe9, 0xa4,
	0x6c, 0x91, 0xf1, 0x16, 0x0e, 0x5a, 0x89, 0x19, 0xf2, 0xb3, 0x21, 0xb1, 0x8e, 0xe3, 0xc9, 0x8a,
	0x4b, 0xb8, 0x43, 0xfe, 0x5c, 0x5e, 0x8f, 0xc6, 0x93, 0xc7, 0x42, 0x4c, 0x56, 0x6e, 0xed, 0x07,
	0x85, 0x66, 0x2a, 0x7d, 0x49, 0x4a, 0xec, 0x83, 0xfa, 0x1d, 0x29, 0x31, 0x31, 0xa6, 0x26, 0xf4,
	0x27, 0xa2, 0xa4, 0x3a, 0xe3, 0xea, 0x21, 0x21, 0x97, 0x5a, 0xe8, 0x0e, 0xc8, 0xc7, 0xd6, 0x45,
	0xa1, 0x96, 0x2a, 0x63, 0xdc, 0xa7, 0x1c, 0x2c, 0x97, 0x04, 0x7a, 0x1a, 0x1d, 0xd6, 0xa1, 0xc9,
	0x29, 0x34, 0x29, 0xe0, 0x3c, 0x3a, 0xa6, 0x83, 0xbb, 0xa6, 0xd1, 0x94, 0x3e, 0xd8, 0x85, 0x62,
	0x39, 0x56, 0xc7, 0x82, 0x7e, 0xc6, 0x2e, 0x14, 0xcb, 0x92, 0x98, 0xd6, 0x5f, 0x59, 0x17, 0x8a,
	0x65, 0x51, 0xbd, 0xa2, 0xfe, 0xc4, 0x14, 0x00, 0x58, 0xb5, 0x4d, 0x3c, 0xa3, 0x1f, 0x40, 0x0b,
	0xc5, 0xf2, 0x34, 0xd4, 0x69, 0xdb, 0x63, 0x32, 0xc7, 0x39, 0x7d, 0xed, 0x3a, 0x20, 0x58, 0x12,
	0x9d, 0xd7, 0x2f, 0xed, 0x3c, 0xf1, 0xd7, 0x62, 0xf9, 0x51, 0x7d, 0x70, 0x9c, 0x92, 0x88, 0xdf,
	0xe3, 0x3e, 0x4c, 0xfc, 0x35, 0x91, 0x21, 0xd3, 0xdf, 0xce, 0x24, 0x11, 0xa6, 0x18, 0x08, 0x95,
	0x54, 0x43, 0x4a, 0x46, 0x46, 0xbd, 0x2e, 0xa4, 0x52, 0xfb, 0x91, 0x63, 0x5d, 0x0b, 0xb8, 0xa1,
	0xaf, 0x1a, 0x67, 0x93, 0x9d, 0xb1, 0xa9, 0x3f, 0x51, 0x44, 0x29, 0x3a, 0xfb, 0xab, 0xad, 0x1f,
	0xa8, 0x9c, 0xeb, 0x40, 0x57, 0xd5, 0xcd, 0x3d, 0x91, 0x48, 0x0d, 0xae, 0xba, 0x7e, 0xac, 0xb0,
	0x4f, 0x67, 0x94, 0xd8, 0x68, 0x17, 0x27, 0xa1, 0x67, 0x32, 0xea, 0x0c, 0xdb, 0xd3, 0x05, 0x89,
	0xe2, 0x5e, 0xcb, 0xa8, 0xc3, 0x62, 0xaf, 0x96, 0x09, 0xcb, 0xfb, 0xb9, 0x8c, 0x1a, 0x0d, 0x07,
	0x74, 0x61, 0x75, 0xe2, 0xff, 0x7c, 0x46, 0x8d, 0x86, 0x5c, 0x17, 0xd9, 0xc1, 0xbe, 0x90, 0x51,
	0xfd, 0x93, 0xbc, 0xc5, 0x31, 0xb0, 0x6d, 0x93, 0x8a, 0xe0, 0x7e, 0x91, 0x51, 0x0d, 0x79, 0x50,
	0x43, 0xd5, 0x36, 0x2b, 0x9e, 0x9c, 0x0d, 0xbf, 0xec, 0x11, 0xa1, 0x40, 0x63, 0xa5, 0xfb, 0x55,
	0x8f, 0x08, 0x05, 0x29, 0xb1, 0x5f, 0x4b, 0xc1, 0xb3, 0xc9, 0x2b, 0xb5, 0xc0, 0x0a, 0x14, 0xc2,
	0x2b, 0x72, 0x9d, 0x5f, 0x38, 0x2b, 0x1e, 0x7e, 0x3e, 0xa3, 0xa6, 0xd8, 0x7e, 0x0d, 0xbe, 0x68,
	0xb6, 0xf9, 0xa1, 0x5b, 0xf1, 0xf0, 0x0b, 0x19, 0x35, 0x75, 0xc6, 0xb4, 0x20, 0x6b, 0x76, 0xe0,
	0x17, 0xfb, 0xc3, 0x65, 0xd3, 0x31, 0x1b, 0x50, 0x59, 0x5d, 0x05, 0x5a, 0xf1, 0xf0, 0x4b, 0x12,
	0xbe, 0x17, 0x9d, 0xe8, 0x19, 0x31, 0xbf, 0xe3, 0x93, 0x75, 0x65, 0xf3, 0x72, 0x46, 0xed, 0x88,
	0x43, 0xba, 0x75, 0x00, 0x56, 0xf1, 0x18, 0x71, 0x1d, 0xbf, 0xe2, 0xe1, 0x57, 0xfa, 0x07, 0x13,
	0xbd, 0x45, 0xd7, 0x68, 0xe0, 0xf3, 0xc8, 0x6f, 0xf6, 0x17, 0x9e, 0xb4, 0x6d, 0x77, 0x43, 0xb2,
	0xaf, 0x4a, 0xf6, 0x4c, 0x72, 0x10, 0x4b, 0x36, 0x2a, 0x72, 0x19, 0x68, 0x03, 0x2a, 0x1e, 0x7e,
	0xad, 0xbf, 0x72, 0x54, 0x93, 0x69, 0x93, 0x99, 0x15, 0x0f, 0xbf, 0xde, 0x5f, 0x79, 0x2a, 0x68,
	0x79, 0x55, 0xde, 0x40, 0x4e, 0x9d, 0x2b, 0xbf, 0x91, 0x51, 0x3b, 0x79, 0x5f, 0x8f, 0xa6, 0x0c,
	0x77, 0xc3, 0x9b, 0x19, 0x35, 0x6d, 0x92, 0x3d, 0x4e, 0x5d, 0x27, 0xd6, 0x68, 0x6f, 0x65, 0xd4,
	0xe0, 0xda, 0x93, 0xc6, 0x24, 0xf3, 0x76, 0x46, 0x5d, 0x92, 0x77, 0xa7, 0x19, 0xb1, 0x09, 0xde,
	0xe9, 0xb5, 0xd5, 0x05, 0x12, 0x86, 0xf4, 0x6e, 0x8f, 0xfd, 0x54, 0x30, 0xa9, 0x65, 0x3a, 0xae,
	0x90, 0xfa, 0x5e, 0x56, 0xdf, 0xa4, 0x82, 0xea, 0x9c, 0xb4, 0xcf, 0x65, 0xd5, 0x87, 0x81, 0x43,
	0x1a, 0x30, 0xb1, 0xe3, 0xbf, 0xdf, 0x5f, 0xb4, 0x03, 0xfe, 0x20, 0xab, 0xdf, 0xa2, 0x1d, 0x51,
	0x59, 0x95, 0x1f, 0x66, 0xf5, 0x5b, 0x54, 0x90, 0x12, 0xfb, 0x51, 0x56, 0x9d, 0xb1, 0xa3, 0xda,
	0x74, 0xf8, 0x7d, 0xe0, 0x46, 0x56, 0xbf, 0xa8, 0xb1, 0xca, 0x84, 0x15, 0xfc, 0xb1, 0x14, 0x4b,
	0xcd, 0x9a, 0x8a, 0xc3, 0x5c, 0xdb, 0x6d, 0xb4, 0x63, 0xe1, 0xfd, 0xb6, 0x87, 0xa4, 0x44, 0x25,
	0xf7, 0xbb, 0xac, 0x7a, 0x85, 0x1f, 0xeb, 0x21, 0xd9, 0xa9, 0xce, 0xef, 0xb3, 0xfa, 0x7b, 0x9a,
	0x84, 0x3b, 0xe4, 0x1f, 0xb6, 0x90, 0x0d, 0x17, 0x9b, 0x9a, 0x8e, 0xbf, 0x0a, 0x14, 0xff, 0x51,
	0xca, 0xa6, 0xc6, 0x58, 0x1c, 0x06, 0x4b, 0xe1, 0x7f, 0x92, 0xda, 0x79, 0x74, 0xb4, 0x17, 0xbe,
	0x4c, 0x58, 0xd3, 0xa2, 0xe6, 0x46, 0xc5, 0x69, 0xe0, 0x3f, 0x4b, 0xf9, 0xf3, 0xe8, 0xee, 0xde,
	0xf2, 0x71, 0x8b, 0xbf, 0x64, 0xd5, 0xc7, 0x87, 0x9e, 0x16, 0x15, 0x87, 0x95, 0xac, 0x25, 0x68,
	0x10, 0x9f, 0xbf, 0xcb, 0xbf, 0x99, 0xd5, 0xcf, 0xb5, 0xa4, 0x8f, 0xa4, 0xcd, 0x5f, 0xa5, 0x97,
	0x0b, 0xe8, 0x54, 0x5f, 0x2f, 0x93, 0x96, 0x35, 0xc9, 0x18, 0x25, 0x2b, 0x01, 0x03, 0x1f, 0xff,
	0x4d, 0xba, 0x7a, 0x00, 0x9d, 0xd9, 0xc2, 0x55, 0xd2, 0xf0, 0xef, 0x59, 0x75, 0x5b, 0x48, 0x6c,
	0x82, 0x25, 0xe2, 0x79, 0x36, 0xc4, 0x7a, 0xe7, 0x89, 0x21, 0xfd, 0x79, 0x1b, 0x81, 0x92, 0xfa,
	0xf4, 0x90, 0xbe, 0xb3, 0x23, 0x4a, 0xec, 0xe6, 0x27, 0x87, 0xf4, 0xbb, 0xa4, 0x03, 0x85, 0x8d,
	0xfd, 0x94, 0xc4, 0x3e, 0x80, 0xc6, 0x13, 0xef, 0xcf, 0xae, 0x03, 0xd4, 0x0d, 0x57, 0xde, 0xac,
	0xf3, 0x19, 0x5f, 0x72, 0x08, 0x93, 0x03, 0xe0, 0x1f, 0x43, 0xea, 0xc5, 0xee, 0xd8, 0x96, 0x46,
	0x7c, 0x9b, 0xfd, 0x53, 0x1a, 0xa4, 0x2a, 0xd7, 0x65, 0x50, 0x05, 0x56, 0x72, 0xbc, 0x40, 0x79,
	0xfa, 0x97, 0x34, 0xdc, 0x2a, 0x3c, 0x69, 0xc8, 0xbd, 0xfd, 0x5b, 0x1a, 0x5d, 0x42, 0x17, 0xb6,
	0x08, 0xcf, 0x0b, 0x98, 0xbf, 0x08, 0xb4, 0x15, 0x30, 0x93, 0xff, 0x42, 0xba, 0xfd, 0x8f, 0x54,
	0xb8, 0x88, 0xee, 0x79, 0x6f, 0x0a, 0xdc, 0xff, 0x5b, 0xd2, 0xfa, 0x41, 0x74, 0x76, 0x6b, 0xeb,
	0xcb, 0xc4, 0x21, 0xd2, 0xef, 0xdb, 0xd2, 0xf2, 0x3e, 0x74, 0x72, 0x30, 0x4b, 0xee, 0xef, 0x1d,
	0x69, 0xf5, 0x10, 0x3a, 0xdf, 0xd7, 0x6a, 0xd2, 0xb6, 0xa3, 0x80, 0xab, 0xa0, 0x2a, 0xfc, 0xee,
	0xa0, 0x4b, 0x13, 0x37, 0xe6, 0x5e, 0xff, 0x3b, 0x68, 0x96, 0xfc, 0x9a, 0x10, 0xb0, 0xd8, 0xa2,
	0xfe, 0x6f, 0xd0, 0x2c, 0x95, 0x25, 0xf7, 0xf7, 0x51, 0x63, 0x40, 0x7f, 0x93, 0xb6, 0x5d, 0x09,
	0x58, 0x2c, 0xc5, 0x8f, 0x19, 0x03, 0xfa, 0x53, 0x96, 0xdc, 0xdf, 0xc7, 0x07, 0xf5, 0x17, 0x7e,
	0xf4, 0x89, 0x37, 0xed, 0x27, 0x06, 0xf5, 0xa7, 0x2c, 0xb9, 0xbf, 0x4f, 0x0e, 0x6a, 0x35, 0x43,
	0x1c, 0xd3, 0x96, 0xbe, 0x3e, 0x65, 0xe8, 0x07, 0xa6, 0xde, 0x8a, 0xfb, 0x79, 0x5c, 0x5a, 0xdc,
	0x8f, 0x4e, 0x77, 0x5b, 0xcc, 0x41, 0xbb, 0xd4, 0x32, 0x1b, 0x50, 0xdc, 0xf4, 0x5c, 0xca, 0xe2,
	0x9b, 0xfe, 0x49, 0x69, 0x97, 0x1a, 0xb4, 0xbd, 0xec, 0xb8, 0xaf, 0xa7, 0xfa, 0xe6, 0x24, 0x6d,
	0xaa, 0x6d, 0xa7, 0x5e, 0x65, 0xa0, 0x6e, 0xeb, 0x9f, 0xe9, 0x9b, 0x53, 0xda, 0x8a, 0xfb, 0xf9,
	0xac, 0xa1, 0x1f, 0xe8, 0xdd, 0x16, 0x89, 0xe2, 0x3d, 0x2d, 0xcd, 0xee, 0x41, 0xc7, 0x07, 0x30,
	0xe3, 0x9e, 0x9e, 0x31, 0xf4, 0xa3, 0x3c, 0x32, 0x89, 0x8d, 0xf2, 0x2f, 0x1a, 0xfa, 0x51, 0x1e,
	0x81, 0x92, 0xfa, 0x92, 0xa1, 0xbf, 0xf5, 0x28, 0xb9, 0x65, 0x93, 0xd5, 0x9b, 0xfc, 0x5c, 0xff,
	0xb2, 0xa1, 0x9f, 0xe7, 0x11, 0xa9, 0xb0, 0xaf, 0x18, 0xfa, 0x17, 0x93, 0xf0, 0x43, 0x51, 0xc4,
	0x4e, 0x13, 0xb3, 0x21, 0x2b, 0xf0, 0x55, 0x43, 0xff, 0x0e, 0x95, 0xc2, 0x79, 0xe6, 0x5f, 0x93,
	0xca, 0xa9, 0xdb, 0xb2, 0x0a, 0xb5, 0xb6, 0x39, 0x07, 0xea, 0x4f, 0x1d, 0x5f, 0x37, 0xf4, 0x17,
	0x96, 0x24, 0xcd, 0x75, 0xbf, 0xd1, 0xb7, 0x47, 0xe6, 0xc9, 0x3a, 0x2c, 0xc1, 0x2a, 0x05, 0xbf,
	0x59, 0x65, 0x26, 0x55, 0xdd, 0xf8, 0xac, 0xa1, 0xbf, 0x5a, 0xe8, 0xad, 0xb8, 0x9f, 0x6f, 0x1a,
	0xfd, 0x8e, 0x92, 0x84, 0x45, 0xa7, 0x15, 0xbf, 0x25, 0xdd, 0x68, 0x4f, 0xba, 0x94, 0x11, 0xf7,
	0xf2, 0xed, 0x41, 0xb3, 0x49, 0x34, 0xe2, 0x77, 0x06, 0xcd, 0x46, 0xf5, 0xe1, 0x77, 0x0d, 0xfd,
	0xa7, 0x80, 0x62, 0xea, 0x8d, 0xfb, 0xa6, 0xa1, 0x7f, 0x3f, 0x28, 0xc6, 0xdf, 0xb7, 0x5f, 0x35,
	0xd4, 0x67, 0x96, 0x5d, 0x29, 0x48, 0xdc, 0x26, 0x5e, 0xeb, 0xd1, 0x27, 0x45, 0xd7, 0xe7, 0x17,
	0xe9, 0xf8, 0xd9, 0xf9, 0x1b, 0x43, 0xff, 0xfe, 0x13, 0x43, 0x79, 0x02, 0xaf, 0x1b, 0xfa, 0xf7,
	0x9f, 0x62, 0xec, 0xc3, 0xc2, 0x1b, 0x42, 0x6a, 0xe2, 0x22, 0xba, 0x75, 0x83, 0x50, 0xb8, 0x42,
	0x9c, 0x91, 0xc3, 0xf9, 0xe8, 0x0f, 0xca, 0x79, 0xf9, 0x07, 0xe5, 0x7c, 0xd1, 0x09, 0x5a, 0xe1,
	0x57, 0x79, 0xf1, 0x32, 0x3a, 0xfa, 0xfc, 0xe3, 0x43, 0x63, 0x99, 0xf1, 0xe1, 0xa5, 0x5b, 0xb8,
	0x4d, 0xc9, 0x99, 0x78, 0x18, 0x0d, 0x87, 0xd6, 0x6e, 0xc0, 0x06, 0x31, 0x7f, 0x41, 0x98, 0x87,
	0x2e, 0x2b, 0x01, 0x9b, 0x98, 0x45, 0x3b, 0x42, 0x7b, 0x8b, 0x6f, 0x8a, 0x01, 0x63, 0x78, 0x51,
	0x88, 0x6c, 0xe3, 0x96, 0xe1, 0x6e, 0x2a, 0x39, 0x13, 0x25, 0xb4, 0x33, 0x26, 0x34, 0x60, 0x38,
	0x2f, 0x09, 0xa5, 0xed, 0x4a, 0x89, 0xc7, 0x74, 0x09, 0xdd, 0x16, 0x4a, 0x31, 0xe2, 0xb4, 0x07,
	0x51, 0x79, 0x59, 0xa8, 0x84, 0x95, 0xa8, 0x11, 0xa7, 0x3d, 0x31, 0x8f, 0x6e, 0x0f, 0x15, 0x56,
	0x5c, 0x97, 0xd9, 0xae, 0x69, 0x01, 0x1d, 0x44, 0xe7, 0x15, 0xa1, 0x13, 0x26, 0x32, 0xa5, 0x4c,
	0x27, 0x0a, 0x28, 0xcc, 0xf4, 0x8a, 0xe3, 0x5e, 0x59, 0xf5, 0x5b, 0x83, 0x28, 0xdd, 0x14, 0x4a,
	0x61, 0x1e, 0x0b, 0xee, 0x8c, 0xdf, 0x9a, 0xba, 0x0f, 0x1d, 0xad, 0xbb, 0xad, 0xbc, 0x6f, 0x32,
	0xd7, 0x6f, 0x12, 0xdb, 0x5c, 0xf1, 0xe5, 0x7f, 0x27, 0xb0, 0xc9, 0x8a, 0x92, 0x9a, 0xda, 0x51,
	0x0b, 0x7f, 0x29, 0xba, 0xe6, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0x0a, 0x5d, 0xd0, 0x86,
	0x20, 0x00, 0x00,
}
